spring:
  application:
    name: vcf-service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

dataset-service:
  ribbon:
    eureka:
      enabled: true